name: "Refetch inspections list by letter"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

jobs:
  scrape:
    name: Clear and refetch four oldest by-letter files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Delete oldest files from inspections-by-letter
        run: 'git ls-tree -r --name-only HEAD data/fetched/inspections-by-letter | while read filename; do echo "$(git log -1 --format="%ad" --date=iso -- "$filename") $filename"; done | sort | grep -o "data/.*" | head -n 4 | xargs rm'

      - name: Fetch inspection list
        run: python scripts/00-fetch-inspection-list.py

      - name: Config git
        run: git config --global user.email "actions@users.noreply.github.com" && git config --global user.name "Automated"

      - name: Commit changes
        run: git add data && (git diff --cached --quiet || git commit -m "Fully refetch inspections list")

      - name: Push changes
        run: git push
